parser: babel-eslint
env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 
  - 'plugin:security/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - security
